# Data cleaning with pandas

In [1]:
import numpy as np
import pandas as pd

In [7]:
# import messy data
df = pd.read_csv("students_data_messy.csv")
print(df.head())

       Name      School Grade  Score   Age  Attendance Extracurricular  \
0  Student1  South High     B   58.2  18.0        97.0          Sports
1  Student2         NaN     F   35.5  17.0        78.0             NaN
2  Student3         NaN     C   77.7  17.0        87.0             Art
3  Student4   West High     F   23.1  16.0        96.0    Science Club
4       NaN  North High     F   90.2  16.0       100.0             NaN

                 Email
0                  NaN
1  student2@school.edu
2  student3@school.edu
3  student4@school.edu
4                  NaN

### step 1 - Dealing with missing values

- Option 1 - Drop rows/columns contains missing values
- Option 2 - Fill missing values with some values (static, avg)

## drop missing values

In [11]:
# Drop any row that has at least 1 missing value
df_dropped = df.dropna()
print(df_dropped.head())

         Name      School Grade  Score   Age  Attendance Extracurricular  \
3    Student4   West High     F   23.1  16.0        96.0    Science Club
6    Student7   West High     B   48.1  18.0        88.0          Sports
9   Student10  South High     C   18.3  17.0        91.0    Science Club
10  Student11  South High     D   16.9  18.0        79.0    Science Club
13  Student14  North High     C   24.3  17.0        84.0    Science Club

                   Email
3    student4@school.edu
6    student7@school.edu
9   student10@school.edu
10  student11@school.edu
13  student14@school.edu

In [21]:
df_dropped_col = df.dropna(subset=["Age"])
print(df_dropped_col.head(10))

        Name      School Grade  Score   Age  Attendance Extracurricular  \
0   Student1  South High     B   58.2  18.0        97.0          Sports
1   Student2         NaN     F   35.5  17.0        78.0             NaN
2   Student3         NaN     C   77.7  17.0        87.0             Art
3   Student4   West High     F   23.1  16.0        96.0    Science Club
4        NaN  North High     F   90.2  16.0       100.0             NaN
5        NaN   West High     F   88.8  18.0        99.0             NaN
6   Student7   West High     B   48.1  18.0        88.0          Sports
7   Student8   West High     C    7.8  16.0         NaN             NaN
8   Student9  South High     D   68.0  17.0        99.0             NaN
9  Student10  South High     C   18.3  17.0        91.0    Science Club

                  Email  Age Filled  Score Filled
0                   NaN        18.0          58.2
1   student2@school.edu        17.0          35.5
2   student3@school.edu        17.0          77.7
3   student4@school.edu        16.0          23.1
4                   NaN        16.0          90.2
5                   NaN        18.0          88.8
6   student7@school.edu        18.0          48.1
7   student8@school.edu        16.0           7.8
8   student9@school.edu        17.0          68.0
9  student10@school.edu        17.0          18.3

### Filling missing values

In [19]:
# Fill missing age values with static number
df["Age Filled"] = df["Age"].fillna(0)
print(df.head(5))

       Name      School Grade  Score   Age  Attendance Extracurricular  \
0  Student1  South High     B   58.2  18.0        97.0          Sports
1  Student2         NaN     F   35.5  17.0        78.0             NaN
2  Student3         NaN     C   77.7  17.0        87.0             Art
3  Student4   West High     F   23.1  16.0        96.0    Science Club
4       NaN  North High     F   90.2  16.0       100.0             NaN

                 Email  Age Filled
0                  NaN        18.0
1  student2@school.edu        17.0
2  student3@school.edu        17.0
3  student4@school.edu        16.0
4                  NaN        16.0

In [22]:
# Filling missing vlaue with avg, mean median
df["Score Filled"] = df["Score"].fillna(df["Score"].mean())
print(df.head(20))

         Name      School Grade  Score   Age  Attendance Extracurricular  \
0    Student1  South High     B   58.2  18.0        97.0          Sports
1    Student2         NaN     F   35.5  17.0        78.0             NaN
2    Student3         NaN     C   77.7  17.0        87.0             Art
3    Student4   West High     F   23.1  16.0        96.0    Science Club
4         NaN  North High     F   90.2  16.0       100.0             NaN
5         NaN   West High     F   88.8  18.0        99.0             NaN
6    Student7   West High     B   48.1  18.0        88.0          Sports
7    Student8   West High     C    7.8  16.0         NaN             NaN
8    Student9  South High     D   68.0  17.0        99.0             NaN
9   Student10  South High     C   18.3  17.0        91.0    Science Club
10  Student11  South High     D   16.9  18.0        79.0    Science Club
11  Student12  North High     F   37.5  17.0         NaN             Art
12  Student13  North High     F   69.7  18.0        96.0             NaN
13  Student14  North High     C   24.3  17.0        84.0    Science Club
14  Student15  South High     F   72.7  17.0        96.0             NaN
15  Student16  North High     A   62.6  18.0       100.0             NaN
16  Student17  South High     B   11.7  17.0         NaN          Sports
17  Student18  South High     B   85.7  17.0        95.0             Art
18  Student19  South High     F   51.8  16.0        82.0             NaN
19  Student20         NaN     A    NaN   NaN        84.0             Art

                   Email  Age Filled  Score Filled
0                    NaN        18.0     58.200000
1    student2@school.edu        17.0     35.500000
2    student3@school.edu        17.0     77.700000
3    student4@school.edu        16.0     23.100000
4                    NaN        16.0     90.200000
5                    NaN        18.0     88.800000
6    student7@school.edu        18.0     48.100000
7    student8@school.edu        16.0      7.800000
8    student9@school.edu        17.0     68.000000
9   student10@school.edu        17.0     18.300000
10  student11@school.edu        18.0     16.900000
11  student12@school.edu        17.0     37.500000
12  student13@school.edu        18.0     69.700000
13  student14@school.edu        17.0     24.300000
14  student15@school.edu        17.0     72.700000
15  student16@school.edu        18.0     62.600000
16  student17@school.edu        17.0     11.700000
17  student18@school.edu        17.0     85.700000
18  student19@school.edu        16.0     51.800000
19  student20@school.edu         0.0     50.804444

### step 2 Filtering helps explore subset of data with specific conditions
### sorting helps quickly finding highest/lowest values

In [26]:
# make df for age over 30
df_17_over = df[df["Age"] > 17]
print(df_17_over)

         Name      School Grade  Score   Age  Attendance Extracurricular  \
0    Student1  South High     B   58.2  18.0        97.0          Sports
5         NaN   West High     F   88.8  18.0        99.0             NaN
6    Student7   West High     B   48.1  18.0        88.0          Sports
10  Student11  South High     D   16.9  18.0        79.0    Science Club
12  Student13  North High     F   69.7  18.0        96.0             NaN
15  Student16  North High     A   62.6  18.0       100.0             NaN
27  Student28   West High     A   66.1  18.0        80.0          Sports
30  Student31  South High     F   35.9  18.0        78.0             Art
31  Student32   West High     D    8.5  18.0        85.0          Sports
32  Student33  South High     B    4.1  18.0        87.0    Science Club
33  Student34  South High     B    NaN  18.0        86.0             Art
34  Student35  North High     B    NaN  18.0        81.0          Sports
36  Student37  South High     A   99.3  18.0        90.0             Art
38  Student39  South High     D   28.9  18.0        88.0             NaN
39  Student40         NaN     F   40.8  18.0        95.0          Sports
45  Student46   West High     F   23.7  18.0         NaN          Sports

                   Email  Age Filled  Score Filled
0                    NaN        18.0     58.200000
5                    NaN        18.0     88.800000
6    student7@school.edu        18.0     48.100000
10  student11@school.edu        18.0     16.900000
12  student13@school.edu        18.0     69.700000
15  student16@school.edu        18.0     62.600000
27  student28@school.edu        18.0     66.100000
30  student31@school.edu        18.0     35.900000
31  student32@school.edu        18.0      8.500000
32  student33@school.edu        18.0      4.100000
33  student34@school.edu        18.0     50.804444
34  student35@school.edu        18.0     50.804444
36                   NaN        18.0     99.300000
38                   NaN        18.0     28.900000
39  student40@school.edu        18.0     40.800000
45  student46@school.edu        18.0     23.700000

In [28]:
# Filter for multiple conditions
high_score = df[(df["Age"] > 17) & (df["Score"] > 90)]
high_score.head()

,Name,School,Grade,Score,Age,Attendance,Extracurricular,Email,Age Filled,Score Filled
36,Student37,South High,A,99.3,18.0,90.0,Art,NaN,18.0,99.3

In [29]:
# Sorting by multiple columns
df_sorted_multi = df.sort_values(by=["Age", "Score"], ascending=[True, False])
df_sorted_multi.head(15)

,Name,School,Grade,Score,Age,Attendance,Extracurricular,Email,Age Filled,Score Filled
41,Student42,North High,D,90.4,16.0,NaN,Science Club,student42@school.edu,16.0,90.400000
4,NaN,North High,F,90.2,16.0,100.0,NaN,NaN,16.0,90.200000
40,Student41,West High,D,90.1,16.0,75.0,Sports,NaN,16.0,90.100000
28,Student29,South High,F,72.7,16.0,93.0,NaN,student29@school.edu,16.0,72.700000
44,Student45,South High,C,68.2,16.0,80.0,Art,student45@school.edu,16.0,68.200000
22,Student23,South High,B,63.3,16.0,88.0,Sports,student23@school.edu,16.0,63.300000
18,Student19,South High,F,51.8,16.0,82.0,NaN,student19@school.edu,16.0,51.800000
29,Student30,NaN,A,32.4,16.0,97.0,Art,student30@school.edu,16.0,32.400000
24,Student25,West High,F,28.4,16.0,96.0,Art,student25@school.edu,16.0,28.400000
3,Student4,West High,F,23.1,16.0,96.0,Science Club,student4@school.edu,16.0,23.100000
26,Student27,West High,F,14.4,16.0,94.0,NaN,student27@school.edu,16.0,14.400000
7,Student8,West High,C,7.8,16.0,NaN,NaN,student8@school.edu,16.0,7.800000
20,Student21,NaN,A,5.5,16.0,88.0,Science Club,student21@school.edu,16.0,5.500000
37,Student38,West High,C,NaN,16.0,76.0,Art,student38@school.edu,16.0,50.804444
42,Student43,North High,F,NaN,16.0,93.0,Art,student43@school.edu,16.0,50.804444

# Renaming columns

In [30]:
# spec column
df_renamed = df.rename(columns={"Age": "Age_years", "Score": "Test_Score"})
df_renamed.head()

,Name,School,Grade,Test_Score,Age_years,Attendance,Extracurricular,Email,Age Filled,Score Filled
0,Student1,South High,B,58.2,18.0,97.0,Sports,NaN,18.0,58.2
1,Student2,NaN,F,35.5,17.0,78.0,NaN,student2@school.edu,17.0,35.5
2,Student3,NaN,C,77.7,17.0,87.0,Art,student3@school.edu,17.0,77.7
3,Student4,West High,F,23.1,16.0,96.0,Science Club,student4@school.edu,16.0,23.1
4,NaN,North High,F,90.2,16.0,100.0,NaN,NaN,16.0,90.2